### PR TITLE
in LDAPDelegate.connect, catch ldap.UNAVAILABLE exceptions

### PR DESCRIPTION
**Pull request by gbastien**

### CODE REVIEW

**Comment by gbastien** [comment]
Hi @dataflake 
this refers #9 
Can you have a look and merge if you think this is OK?
A new release would be great too :-)
Thank you,
Gauthier

**Comment by dataflake** [comment]
One problem I can see straight away is those strange version numbers you use. Those do not belong in the official repository.

**Comment by gbastien** [comment]
Sorry I did a local release with the forked branch and it changed in the PR as well...
This is fixed, thank you for review!
Gauthier

**Comment by dataflake** [comment]
I am not comfortable making any further changes to the 2.x branch or any releases from it. I do not even have an environment where I can run the tests anymore. Creating an official release would be saying "this is still supported and I stand behind it", but that is wrong.

It looks like you already have a workaround with your local release so you're all set.

**Pull request closed without merging**
